//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strahovoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Ychet_Polisov = new HashSet<Ychet_Polisov>();
        }
    
        public int Client_ID { get; set; }
        public string Client_FName { get; set; }
        public string Client_Name { get; set; }
        public string Client_Otchestvo { get; set; }
        public Nullable<System.DateTime> Client_BDay { get; set; }
        public string Client_Adres { get; set; }
        public string Client_Passport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ychet_Polisov> Ychet_Polisov { get; set; }
    }
}
