//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strahovoe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class de9Entities1 : DbContext
    {
        public de9Entities1()
            : base("name=de9Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static de9Entities1 _context;

        public static de9Entities1 GetContext()
        {
            if (_context == null)
                _context = new de9Entities1();


            return _context;

        }

        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<Ychet_Polisov> Ychet_Polisov { get; set; }
    }
}
