//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strahovoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ychet_Polisov
    {
        public int Polis_ID { get; set; }
        public int Usluga_ID { get; set; }
        public int Client_ID { get; set; }
        public string Client_Passport { get; set; }
        public Nullable<System.DateTime> Polis_Date { get; set; }
        public Nullable<System.DateTime> Polis_Srok { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
